
(defun inspiration-699643 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-699643
     ((background-color . "#0F0307")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#5C405B"))))
     (font-lock-constant-face ((t (:foreground "#FFBE00"))))
     (font-lock-builtin-face ((t (:foreground "#D0426F"))))
     (font-lock-function-name-face ((t (:foreground "#919E73"))))
     (font-lock-variable-name-face ((t (:foreground "#AEBC55"))))
     (font-lock-keyword-face ((t (:foreground "#FF5400"))))
     (font-lock-string-face ((t (:foreground "#CEB50B"))))
     (font-lock-doc-string-face ((t (:foreground "#CEB50B"))))
     (font-lock-type-face ((t (:foreground "#FF7524"))))
     )))

(provide 'inspiration-699643)