
(defun inspiration-785613 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-785613
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FF6511"))))
     (font-lock-constant-face ((t (:foreground "#7B7F02"))))
     (font-lock-builtin-face ((t (:foreground "#D84E00"))))
     (font-lock-function-name-face ((t (:foreground "#457E2A"))))
     (font-lock-variable-name-face ((t (:foreground "#FF8800"))))
     (font-lock-keyword-face ((t (:foreground "#DA6760"))))
     (font-lock-string-face ((t (:foreground "#FF3900"))))
     (font-lock-doc-string-face ((t (:foreground "#FF3900"))))
     (font-lock-type-face ((t (:foreground "#FF4500"))))
     )))

(provide 'inspiration-785613)