
(defun inspiration-905833 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-905833
     ((background-color . "#00060E")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#B300D8"))))
     (font-lock-constant-face ((t (:foreground "#EF8CAE"))))
     (font-lock-builtin-face ((t (:foreground "#D60D65"))))
     (font-lock-function-name-face ((t (:foreground "#7FB616"))))
     (font-lock-variable-name-face ((t (:foreground "#6800F8"))))
     (font-lock-keyword-face ((t (:foreground "#CE90FF"))))
     (font-lock-string-face ((t (:foreground "#0034ED"))))
     (font-lock-doc-string-face ((t (:foreground "#0034ED"))))
     (font-lock-type-face ((t (:foreground "#D900AE"))))
     )))

(provide 'inspiration-905833)