

(defun color-theme-install-random ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(color-theme-install-random
     ((background-color . "#0A0004")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#00FF00"))))
     (font-lock-constant-face ((t (:foreground "#4C7E6F"))))
     (font-lock-builtin-face ((t (:foreground "#695C4D"))))
     (font-lock-function-name-face ((t (:foreground "#26C738"))))
     (font-lock-variable-name-face ((t (:foreground "#289841"))))
     (font-lock-keyword-face ((t (:foreground "#4A9724"))))
     (font-lock-string-face ((t (:foreground "#0DFF00"))))
     (font-lock-doc-string-face ((t (:foreground "#0DFF00"))))
     (font-lock-type-face ((t (:foreground "#8E00FF"))))
     )))

(provide 'color-theme-install-random)