#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/X11/lib/X11/xinit/.Xresources
sysmodmap=/usr/X11/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    if [ -x /usr/bin/cpp ] ; then
        xrdb -merge $sysresources
    else
        xrdb -nocpp -merge $sysresources
    fi
fi


if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi


if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        xrdb -merge "$userresources"
    else
        xrdb -nocpp -merge "$userresources"
    fi
fi


if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi
# start some nice programs

# if [ -d /usr/X11/lib/X11/xinit/xinitrc.d ] ; then
# 	for f in /usr/X11/lib/X11/xinit/xinitrc.d/*.sh ; do
# 		[ -x "$f" ] && . "$f"
# 	done
# 	unset f
# fi
#### fonts config
/usr/X11/lib/X11/xinit/xinitrc.d/10-fontdir.sh
xset fp+ ~/sw/fonts
xset fp rehash
cd
####

#### tiling wm config
quartz-wm --only-proxy &
/usr/local/bin/xmonad &
#/opt/local/bin/awesome &
#/opt/local/bin/ratpoison &
# ~/sw/bin/dwm
#twm &			       
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login
/opt/local/bin/rxvt


