(defvar crossconf-emacs-dir '"~/Dropbox/crossconf/emacs.d")
(defvar emacs-app-site-lisp-dir '"/Applications/Emacs.app/Contents/Resources/site-lisp")
(add-to-list 'load-path crossconf-emacs-dir)
(load-file "hmoo.el")
;;(load-file ~/Dropbox/crossconf/emacs.d)
