(defun hmoo1 ()
  (interactive)
  (color-theme-install
   '(hmoo1
      ((background-color . "#1f102e")
      (background-mode . light)
      (border-color . "#383838")
      (cursor-color . "#fce94f")
      (foreground-color . "#b7b79a")
      (mouse-color . "black"))
     (fringe ((t (:background "#383838"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#4f4f4f"))))
     (region ((t (:background "#404040"))))
     (font-lock-builtin-face ((t (:foreground "#147ef0"))))
     (font-lock-comment-face ((t (:foreground "#3e4328"))))
     (font-lock-function-name-face ((t (:foreground "#25fe16"))))
     (font-lock-keyword-face ((t (:foreground "#72aacf"))))
     (font-lock-string-face ((t (:foreground "#dd225c"))))
     (font-lock-type-face ((t (:foreground"#e27b34"))))
     (font-lock-variable-name-face ((t (:foreground "#e4e4a5"))))
     (minibuffer-prompt ((t (:foreground "#6b70ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'hmoo1)