
(defun inspiration-828731 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-828731
     ((background-color . "#000000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FFFF52"))))
     (font-lock-constant-face ((t (:foreground "#FFFF00"))))
     (font-lock-builtin-face ((t (:foreground "#859900"))))
     (font-lock-function-name-face ((t (:foreground "#B1D39E"))))
     (font-lock-variable-name-face ((t (:foreground "#F8D38F"))))
     (font-lock-keyword-face ((t (:foreground "#D9FFB7"))))
     (font-lock-string-face ((t (:foreground "#ECE200"))))
     (font-lock-doc-string-face ((t (:foreground "#ECE200"))))
     (font-lock-type-face ((t (:foreground "#FFFF94"))))
     )))

(provide 'inspiration-828731)