
(defun inspiration-533415 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-533415
     ((background-color . "#001303")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#BB8081"))))
     (font-lock-constant-face ((t (:foreground "#8165DB"))))
     (font-lock-builtin-face ((t (:foreground "#B386FF"))))
     (font-lock-function-name-face ((t (:foreground "#A834E5"))))
     (font-lock-variable-name-face ((t (:foreground "#FFB7FF"))))
     (font-lock-keyword-face ((t (:foreground "#4900FF"))))
     (font-lock-string-face ((t (:foreground "#A587FF"))))
     (font-lock-doc-string-face ((t (:foreground "#A587FF"))))
     (font-lock-type-face ((t (:foreground "#DAA78E"))))
     )))

(provide 'inspiration-533415)