
(defun inspiration-719371 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-719371
     ((background-color . "#0C0913")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#FFC700"))))
     (font-lock-constant-face ((t (:foreground "#D8AE0D"))))
     (font-lock-builtin-face ((t (:foreground "#FF3329"))))
     (font-lock-function-name-face ((t (:foreground "#9FFB74"))))
     (font-lock-variable-name-face ((t (:foreground "#DF3368"))))
     (font-lock-keyword-face ((t (:foreground "#FAE300"))))
     (font-lock-string-face ((t (:foreground "#F0C22F"))))
     (font-lock-doc-string-face ((t (:foreground "#F0C22F"))))
     (font-lock-type-face ((t (:foreground "#FF6F33"))))
     )))

(provide 'inspiration-719371)