
(defun inspiration-722632 ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(inspiration-722632
     ((background-color . "#010307")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#23FFFF"))))
     (font-lock-constant-face ((t (:foreground "#13D1FF"))))
     (font-lock-builtin-face ((t (:foreground "#002CFF"))))
     (font-lock-function-name-face ((t (:foreground "#26FFC3"))))
     (font-lock-variable-name-face ((t (:foreground "#6FA8FF"))))
     (font-lock-keyword-face ((t (:foreground "#1DFF8B"))))
     (font-lock-string-face ((t (:foreground "#3B97FF"))))
     (font-lock-doc-string-face ((t (:foreground "#3B97FF"))))
     (font-lock-type-face ((t (:foreground "#80FFBA"))))
     )))

(provide 'inspiration-722632)