

(defun color-theme-install-random ()
  "Theme generated by http://inspiration.sweyla.com/code/"
  (interactive)
  (color-theme-install
   '(color-theme-install-random
     ((background-color . "#030000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#CFBB32"))))
     (font-lock-constant-face ((t (:foreground "#B5FF7E"))))
     (font-lock-builtin-face ((t (:foreground "#FF8C00"))))
     (font-lock-function-name-face ((t (:foreground "#FF1900"))))
     (font-lock-variable-name-face ((t (:foreground "#FFC562"))))
     (font-lock-keyword-face ((t (:foreground "#FF5C00"))))
     (font-lock-string-face ((t (:foreground "#93808D"))))
     (font-lock-doc-string-face ((t (:foreground "#93808D"))))
     (font-lock-type-face ((t (:foreground "#FFE36B"))))
     )))

(provide 'color-theme-install-random)